/*
===============================================================================
PROJECT: Retail Sales Performance & Customer Segmentation Analysis
DATABASE: SQL Server
DATASET: Online Retail

PURPOSE
-------
This SQL script answers the key business questions for the retail business:

1. What is the overall revenue generated by the business?
2. Which countries generate the most revenue?
3. Who are the highest-value customers?
4. How does revenue change month by month, and is there seasonality?
5. Which products generate the most revenue?
6. When are customers most likely to place orders?
7. What is the Average Order Value (AOV)?
8. Which customers are Champions / Active / Regular / At Risk based on RFM?

RFM = Recency, Frequency, Monetary

KEY SQL CONCEPTS
----------------
- Views
- Data cleaning and validation
- Aggregate functions
- GROUP BY / ORDER BY
- Date functions
- Common Table Expressions (CTEs)
- Window functions / NTILE()
- CASE statements
- Customer segmentation

NOTE
----
The RFM section uses a CTE to make the calculation easier to read and maintain.
For Recency, a LOWER number is better, so Recency is ranked in ASCENDING order.
For Frequency and Monetary, HIGHER values are better, so they are ranked
in ASCENDING order and the resulting NTILE score is reversed where required.
===============================================================================
*/


/*
===============================================================================
SECTION 1 — DATA CLEANING VIEW
Business purpose:
Create one reusable cleaned dataset before performing any analysis.

Cleaning rules:
- Exclude customers with missing CustomerID
- Exclude cancelled invoices (InvoiceNo beginning with 'C')
- Keep only numeric Quantity and UnitPrice values
- Convert Quantity, UnitPrice and InvoiceDate into usable data types
- Calculate line-level revenue as Quantity × UnitPrice
===============================================================================
*/

CREATE OR ALTER VIEW dbo.vw_CleanedRetail AS
SELECT
    InvoiceNo,
    StockCode,
    Description,
    TRY_CAST(Quantity AS FLOAT) AS Quantity,
    TRY_CONVERT(DATETIME, InvoiceDate, 105) AS InvoiceDate,
    TRY_CAST(UnitPrice AS FLOAT) AS UnitPrice,
    CustomerID,
    Country,

    -- Revenue generated by each invoice line
    TRY_CAST(Quantity AS FLOAT) * TRY_CAST(UnitPrice AS FLOAT) AS TotalPrice

FROM dbo.online_retail

WHERE
    CustomerID IS NOT NULL
    AND InvoiceNo NOT LIKE 'C%'
    AND ISNUMERIC(Quantity) = 1
    AND ISNUMERIC(UnitPrice) = 1;


/*
===============================================================================
SECTION 2 — OVERALL BUSINESS PERFORMANCE

Business Question:
What is the overall revenue generated by the business?

Why it matters:
Provides the baseline revenue KPI used to evaluate overall business performance.
===============================================================================
*/

SELECT
    ROUND(SUM(TotalPrice), 2) AS Overall_Revenue
FROM dbo.vw_CleanedRetail;


/*
===============================================================================
SECTION 3 — REVENUE BY COUNTRY

Business Question:
Which countries generate the most revenue?

Why it matters:
Helps identify the strongest geographic markets and supports decisions around
marketing investment, market expansion and resource allocation.
===============================================================================
*/

SELECT
    Country,
    ROUND(SUM(TotalPrice), 2) AS Revenue
FROM dbo.vw_CleanedRetail
GROUP BY Country
ORDER BY Revenue DESC;


/*
===============================================================================
SECTION 4 — HIGHEST-VALUE CUSTOMERS

Business Question:
Who are the highest-value customers based on total spending?

Why it matters:
Identifies customers contributing the most revenue and provides a starting
point for VIP treatment, retention campaigns and customer lifetime value work.
===============================================================================
*/

SELECT TOP 10
    CustomerID,
    ROUND(SUM(TotalPrice), 2) AS Customer_Revenue
FROM dbo.vw_CleanedRetail
GROUP BY CustomerID
ORDER BY Customer_Revenue DESC;


/*
===============================================================================
SECTION 5 — MONTHLY REVENUE TREND

Business Question:
How does revenue change over time, and are there seasonal patterns?

Why it matters:
Helps management identify growth periods, seasonal peaks and slower months
for demand planning, inventory management and promotional campaigns.
===============================================================================
*/

SELECT
    FORMAT(InvoiceDate, 'yyyy-MM') AS Month,
    ROUND(SUM(TotalPrice), 2) AS Revenue
FROM dbo.vw_CleanedRetail
GROUP BY FORMAT(InvoiceDate, 'yyyy-MM')
ORDER BY Month;


/*
===============================================================================
SECTION 6 — TOP-PERFORMING PRODUCTS

Business Question:
Which products generate the most revenue?

Why it matters:
Identifies high-performing products that may require stronger inventory
availability, merchandising focus and promotional support.
===============================================================================
*/

SELECT TOP 20
    Description,
    ROUND(SUM(TotalPrice), 2) AS Revenue
FROM dbo.vw_CleanedRetail
GROUP BY Description
ORDER BY Revenue DESC;


/*
===============================================================================
SECTION 7 — PEAK SHOPPING HOURS

Business Question:
When are customers most likely to place orders?

Why it matters:
Helps optimize marketing campaign timing, staffing and operational capacity
around the hours when customer demand is highest.
===============================================================================
*/

SELECT
    DATEPART(HOUR, InvoiceDate) AS Order_Hour,
    COUNT(DISTINCT InvoiceNo) AS Number_of_Orders
FROM dbo.vw_CleanedRetail
GROUP BY DATEPART(HOUR, InvoiceDate)
ORDER BY Number_of_Orders DESC;


/*
===============================================================================
SECTION 8 — BASIC KPI: TOTAL ORDERS

Business Question:
How many completed orders were placed?

Why it matters:
Provides a core volume KPI and supports calculation of Average Order Value.
===============================================================================
*/

SELECT
    COUNT(DISTINCT InvoiceNo) AS Total_Orders
FROM dbo.vw_CleanedRetail;


/*
===============================================================================
SECTION 9 — BASIC KPI: AVERAGE ORDER VALUE (AOV)

Business Question:
What is the average revenue generated per order?

Formula:
AOV = Total Revenue / Number of Orders

Why it matters:
Helps measure the average value of each transaction and can be used to
evaluate upselling, cross-selling and promotional strategies.
===============================================================================
*/

SELECT
    ROUND(
        SUM(TotalPrice) * 1.0 / COUNT(DISTINCT InvoiceNo),
        2
    ) AS Average_Order_Value
FROM dbo.vw_CleanedRetail;


/*
===============================================================================
SECTION 10 — RFM BASE TABLE

Business Question:
What is the purchasing behaviour of each customer?

RFM measures:
- Recency  = How recently did the customer purchase?
- Frequency = How often did the customer purchase?
- Monetary = How much did the customer spend?

Why it matters:
RFM converts transaction-level data into customer-level behaviour metrics,
which can then be used to create actionable customer segments.
===============================================================================
*/

CREATE OR ALTER VIEW dbo.vw_RFM AS
SELECT
    CustomerID,

    -- Days since the customer's most recent purchase
    DATEDIFF(
        DAY,
        MAX(InvoiceDate),
        (SELECT MAX(InvoiceDate) FROM dbo.vw_CleanedRetail)
    ) AS Recency,

    -- Number of distinct orders placed by the customer
    COUNT(DISTINCT InvoiceNo) AS Frequency,

    -- Total customer spending
    ROUND(SUM(TotalPrice), 2) AS Monetary

FROM dbo.vw_CleanedRetail
GROUP BY CustomerID;


/*
===============================================================================
SECTION 11 — RFM SCORING USING CTE

Business Question:
How can customers be ranked from low-value to high-value based on RFM?

Scoring logic:
- Recency: 5 = most recent customer, 1 = least recent customer
- Frequency: 5 = most frequent customer, 1 = least frequent customer
- Monetary: 5 = highest-spending customer, 1 = lowest-spending customer

Important:
Recency is ranked ASC because a smaller number of days means a more recent
purchase. Frequency and Monetary are ranked ASC and then reversed so that
higher values receive a higher score.

Why use a CTE?
The CTE keeps the RFM ranking step separate from the final scoring step,
making the query easier to understand, test and maintain.
===============================================================================
*/

WITH RFM_Ranked AS
(
    SELECT
        CustomerID,
        Recency,
        Frequency,
        Monetary,

        -- Lower Recency is better, therefore ASC.
        -- NTILE(5) creates five approximately equal groups.
        -- Reversing the result makes 5 = best Recency.
        6 - NTILE(5) OVER (ORDER BY Recency ASC) AS R_Score,

        -- Higher Frequency is better.
        NTILE(5) OVER (ORDER BY Frequency ASC) AS F_Score,

        -- Higher Monetary value is better.
        NTILE(5) OVER (ORDER BY Monetary ASC) AS M_Score

    FROM dbo.vw_RFM
)

SELECT
    CustomerID,
    Recency,
    Frequency,
    Monetary,
    R_Score,
    F_Score,
    M_Score,

    -- Combined three-digit RFM score, e.g. 555 = strongest RFM profile
    CONCAT(R_Score, F_Score, M_Score) AS RFM_Score,

    -- Total RFM score ranges from 3 to 15
    R_Score + F_Score + M_Score AS RFM_Total_Score,

    /*
    Business-friendly customer segmentation.

    12–15 = Active Customers
     8–11 = Regular Customers
      3–7 = At Risk Customers
    */
    CASE
        WHEN R_Score + F_Score + M_Score >= 12
            THEN 'Active Customers'
        WHEN R_Score + F_Score + M_Score >= 8
            THEN 'Regular Customers'
        ELSE 'At Risk Customers'
    END AS Customer_Segment

INTO dbo.RFM_Scored
FROM RFM_Ranked;


/*
===============================================================================
SECTION 12 — FINAL RFM CUSTOMER TABLE

Business Question:
What does the final customer segmentation look like?

Use this output in Power BI to analyze:
- Customer count by segment
- Revenue by segment
- Average RFM score
- At-Risk customer opportunities
===============================================================================
*/

SELECT
    CustomerID,
    Recency,
    Frequency,
    Monetary,
    R_Score,
    F_Score,
    M_Score,
    RFM_Score,
    RFM_Total_Score,
    Customer_Segment
FROM dbo.RFM_Scored
ORDER BY RFM_Total_Score DESC, Monetary DESC;


/*
===============================================================================
SECTION 13 — HIGHEST-VALUE RFM CUSTOMERS

Business Question:
Which customers have the strongest possible RFM profile?

RFM Score 555 means:
- Very recent purchase
- Very high purchase frequency
- Very high monetary value

These customers are potential VIP / loyalty customers.
===============================================================================
*/

SELECT
    CustomerID,
    Recency,
    Frequency,
    Monetary,
    RFM_Score,
    RFM_Total_Score,
    Customer_Segment
FROM dbo.RFM_Scored
WHERE RFM_Score = '555'
ORDER BY Monetary DESC;


/*
===============================================================================
SECTION 14 — CUSTOMER SEGMENT SUMMARY

Business Question:
How many customers are in each RFM segment, and how much revenue does
each segment contribute?

Why it matters:
This is one of the most important outputs for the Power BI customer
segmentation dashboard because it connects customer behaviour with
business value.
===============================================================================
*/

SELECT
    Customer_Segment,
    COUNT(*) AS Customer_Count,
    ROUND(SUM(Monetary), 2) AS Segment_Revenue,
    ROUND(AVG(Monetary), 2) AS Average_Customer_Revenue,
    ROUND(AVG(RFM_Total_Score), 2) AS Average_RFM_Score
FROM dbo.RFM_Scored
GROUP BY Customer_Segment
ORDER BY Segment_Revenue DESC;


/*
===============================================================================
SECTION 15 — AT-RISK CUSTOMER OPPORTUNITY

Business Question:
Which At-Risk customers should the business prioritize for re-engagement?

Why it matters:
At-Risk customers have weaker recent purchasing behaviour and may represent
an opportunity for targeted retention campaigns.

Suggested business actions:
- Personalized offers
- Win-back campaigns
- Product recommendations
- Reminder emails
- Loyalty incentives
===============================================================================
*/

SELECT
    CustomerID,
    Recency,
    Frequency,
    Monetary,
    RFM_Score,
    RFM_Total_Score
FROM dbo.RFM_Scored
WHERE Customer_Segment = 'At Risk Customers'
ORDER BY Monetary DESC;


/*
===============================================================================
END OF ANALYSIS

Recommended Power BI outputs:
- Overall Revenue
- Total Orders
- Average Order Value
- Monthly Revenue Trend
- Revenue by Country
- Top Products
- Peak Shopping Hours
- Customer Count by RFM Segment
- Revenue by RFM Segment
- At-Risk Customer Revenue Opportunity
===============================================================================
*/

