/*
===============================================================================
PROJECT: Retail Sales Performance & Customer Segmentation Analysis
DATABASE: SQL Server

BUSINESS OBJECTIVE
------------------
Use customer transaction history to understand purchasing behaviour and
identify customers who should be retained, nurtured, or re-engaged.

RFM = Recency + Frequency + Monetary

This script answers the following business questions:
1. What is each customer's purchasing behaviour?
2. Which customers are the most valuable?
3. Which customers are at risk of becoming inactive?
4. How can customers be grouped into actionable RFM segments?
5. How many customers and how much revenue does each segment contribute?

RFM DEFINITIONS
---------------
Recency  : How many days since the customer's most recent purchase?
Frequency: How many distinct orders has the customer placed?
Monetary : How much has the customer spent in total?

SCORING LOGIC
-------------
R Score: 5 = most recent purchase, 1 = least recent
F Score: 5 = highest purchase frequency, 1 = lowest frequency
M Score: 5 = highest spending, 1 = lowest spending

IMPORTANT:
Recency is ranked ASCENDING because fewer days since purchase is better.
Frequency and Monetary are ranked ASCENDING and the resulting NTILE score
is reversed so that higher values receive higher scores.
===============================================================================
*/


/*
===============================================================================
1. CUSTOMER-LEVEL RFM METRICS

Business Question:
What is the purchasing behaviour of each customer?

Approach:
- Find the customer's latest purchase date.
- Calculate days since the latest purchase (Recency).
- Count distinct invoices (Frequency).
- Sum customer revenue (Monetary).

The CTE keeps the calculation readable and makes the RFM logic easier to
modify later.
===============================================================================
*/

WITH Customer_RFM AS
(
    SELECT
        CustomerID,

        /*
        RECENCY
        Number of days between the customer's last purchase and the
        latest transaction date available in the cleaned dataset.
        Lower Recency = better customer engagement.
        */
        DATEDIFF
        (
            DAY,
            MAX(InvoiceDate),
            (SELECT MAX(InvoiceDate) FROM dbo.vw_CleanedRetail)
        ) AS Recency,

        /* FREQUENCY
           Number of distinct orders placed by the customer. */
        COUNT(DISTINCT InvoiceNo) AS Frequency,

        /* MONETARY
           Total revenue generated by the customer. */
        SUM(TotalPrice) AS Monetary

    FROM dbo.vw_CleanedRetail
    GROUP BY CustomerID
),


/*
===============================================================================
2. RFM SCORING

Business Question:
How can customers be ranked based on Recency, Frequency and Monetary value?

NTILE(5) divides customers into five approximately equal groups.
===============================================================================
*/

RFM_Scored AS
(
    SELECT
        CustomerID,
        Recency,
        Frequency,
        Monetary,

        /*
        RECENCY SCORE
        Lower Recency is better, therefore ASCENDING order is used.
        NTILE gives 1 to the least-recent group and 5 to the most-recent group.
        */
        NTILE(5) OVER
        (
            ORDER BY Recency DESC
        ) AS Recency_Raw,

        /*
        FREQUENCY SCORE
        Higher Frequency is better.
        */
        NTILE(5) OVER
        (
            ORDER BY Frequency ASC
        ) AS Frequency_Raw,

        /*
        MONETARY SCORE
        Higher Monetary value is better.
        */
        NTILE(5) OVER
        (
            ORDER BY Monetary ASC
        ) AS Monetary_Raw

    FROM Customer_RFM
),


/*
===============================================================================
3. FINAL RFM SCORE

Convert the raw scores into business-friendly 1-5 scores and create:
- RFM Score       : e.g. 555, 453, 215
- RFM Total Score : Sum of R + F + M, ranging from 3 to 15
===============================================================================
*/

RFM_Final AS
(
    SELECT
        CustomerID,
        Recency,
        Frequency,
        Monetary,

        /* Reverse Recency so 5 = most recent and 1 = least recent. */
        6 - Recency_Raw AS R_Score,

        /* Frequency and Monetary already have 5 = highest value. */
        Frequency_Raw AS F_Score,
        Monetary_Raw AS M_Score

    FROM RFM_Scored
)


/*
===============================================================================
4. CUSTOMER SEGMENTATION

Business Question:
Which customers should the business prioritize for retention and engagement?

Segment definitions:
- Active Customers : RFM Total Score 12-15
- Regular Customers: RFM Total Score 8-11
- At Risk Customers: RFM Total Score 3-7

These thresholds can be adjusted later based on business requirements.
===============================================================================
*/

SELECT
    CustomerID,
    Recency,
    Frequency,
    ROUND(Monetary, 2) AS Monetary,

    R_Score,
    F_Score,
    M_Score,

    /* Three-digit RFM score, e.g. 555 = strongest profile. */
    CONCAT(R_Score, F_Score, M_Score) AS RFM_Score,

    /* Overall RFM strength. */
    R_Score + F_Score + M_Score AS RFM_Total_Score,

    /* Business-friendly customer segment. */
    CASE
        WHEN R_Score + F_Score + M_Score >= 12
            THEN 'Active Customers'

        WHEN R_Score + F_Score + M_Score >= 8
            THEN 'Regular Customers'

        ELSE 'At Risk Customers'
    END AS Customer_Segment

INTO dbo.RFM_Scored
FROM RFM_Final;


/*
===============================================================================
5. CUSTOMER SEGMENT OUTPUT

Business Question:
What does the final customer-level segmentation look like?

This result can be exported to Power BI for dashboard analysis.
===============================================================================
*/

SELECT
    CustomerID,
    Recency,
    Frequency,
    ROUND(Monetary, 2) AS Monetary,
    R_Score,
    F_Score,
    M_Score,
    RFM_Score,
    RFM_Total_Score,
    Customer_Segment
FROM dbo.RFM_Scored
ORDER BY
    RFM_Total_Score DESC,
    Monetary DESC;


/*
===============================================================================
6. HIGHEST-VALUE CUSTOMERS

Business Question:
Who are the customers with the strongest possible RFM profile?

RFM 555 means:
- Very recent purchase
- Very high purchase frequency
- Very high monetary value

Business use:
These customers can be targeted with VIP offers, loyalty rewards,
exclusive product launches and retention campaigns.
===============================================================================
*/

SELECT
    CustomerID,
    Recency,
    Frequency,
    ROUND(Monetary, 2) AS Monetary,
    RFM_Score,
    RFM_Total_Score,
    Customer_Segment
FROM dbo.RFM_Scored
WHERE RFM_Score = '555'
ORDER BY Monetary DESC;


/*
===============================================================================
7. CUSTOMER SEGMENT SUMMARY

Business Question:
How many customers are in each segment and how much revenue does each
segment contribute?

Business use:
This connects customer behaviour with business value and helps management
prioritize retention and marketing investment.
===============================================================================
*/

SELECT
    Customer_Segment,
    COUNT(*) AS Customer_Count,
    ROUND(SUM(Monetary), 2) AS Segment_Revenue,
    ROUND(AVG(Monetary), 2) AS Average_Customer_Revenue,
    ROUND(AVG(RFM_Total_Score), 2) AS Average_RFM_Score
FROM dbo.RFM_Scored
GROUP BY Customer_Segment
ORDER BY Segment_Revenue DESC;


/*
===============================================================================
8. AT-RISK CUSTOMER LIST

Business Question:
Which At-Risk customers should be prioritized for re-engagement?

Business use:
Prioritize customers with higher historical spending first, because winning
back a previously valuable customer can have a greater revenue impact.

Possible actions:
- Win-back offers
- Personalized discounts
- Product recommendations
- Reminder campaigns
- Loyalty incentives
===============================================================================
*/

SELECT
    CustomerID,
    Recency,
    Frequency,
    ROUND(Monetary, 2) AS Monetary,
    RFM_Score,
    RFM_Total_Score
FROM dbo.RFM_Scored
WHERE Customer_Segment = 'At Risk Customers'
ORDER BY Monetary DESC;


/*
===============================================================================
END OF RFM ANALYSIS

POWER BI RECOMMENDATIONS
------------------------
Use dbo.RFM_Scored to build visuals for:
- Customer Count by Segment
- Revenue by Segment
- Average Customer Revenue by Segment
- Average RFM Score by Segment
- Top RFM Customers
- At-Risk Customer Revenue Opportunity

BUSINESS STORY
--------------
The analysis moves from transaction-level data to customer-level behaviour,
then converts that behaviour into actionable customer segments. This allows
marketing and CRM teams to focus resources on customers based on their value
and likelihood of continued engagement.
===============================================================================
*/
